### ISSUE TITLE
Don't block chapter sidebar

### ISSUE THREAD

**Issue by mchangrh** [mchangrh/yt-neuter#14]
#4 is blocking the chapter sidebar popups

**Comment by mini-bomba** [comment]
I blame [ce4d99f7](https://github.com/mchangrh/yt-neuter/commit/ce4d99f7c982b4fc82ac10355481c9bd2d88a7c7) instead

**Comment by mchangrh** [comment]
I think we might need to go through rules to make them heirachy specific

**Comment by mchangrh** [comment]
this was also superceded, pretty sure it was #13
