### ISSUE TITLE
Today's videos in subscriptions are block by the main filter

### ISSUE THREAD

**Issue by unbeatable-101** [mchangrh/yt-neuter#21]
<img width="1121" alt="Screenshot 2022-12-09 at 16 18 47" src="https://user-images.githubusercontent.com/58151048/206797736-4d0bca0f-9048-47a0-85a2-eab6a0ed22be.png">
Filter off

<img width="1101" alt="Screenshot 2022-12-09 at 16 19 05" src="https://user-images.githubusercontent.com/58151048/206797752-943d2b45-f287-47db-84fc-c1783c7182f6.png">
Filter on

**Comment by mchangrh** [comment]
can't seem to replicate 🤔

**Comment by mchangrh** [comment]
just to confirm, you mean at https://www.youtube.com/feed/subscriptions, right?

**Comment by unbeatable-101** [comment]
Yes

**Comment by unbeatable-101** [comment]
Huh, I just went to the page, and it seems to work fine now.

**Comment by mchangrh** [comment]
Turns out this would hide days if it had any fundraisers https://github.com/mchangrh/yt-neuter/commit/31b9b55012a23e67d57495c9b5f98659dd31eef3

reverted while I try to replicate the issue
