### ISSUE TITLE
[tracking] generics for filters

### ISSUE THREAD

**Issue by mchangrh** [mchangrh/yt-neuter#23]
with success from generic blocks in noshorts (https://github.com/mchangrh/yt-neuter/commit/b53142a954fbfed3ebe565903aad662f6063a2cc)

see if generics will work on other filters, and where they might break since most of the syntax is identical

**Comment by mchangrh** [comment]
getting it working with :upwards() procedural filter https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters

**Comment by mchangrh** [comment]
Everything tested, looking good so far

**Comment by erkinalp** [comment]
related: ajayyy/sponsorblock#1308
