### ISSUE TITLE
[reflow] more elements per shelf

### ISSUE THREAD

**Issue by mchangrh** [mchangrh/yt-neuter#27]
On channel pages, elements are left-aligned and don't reflow accordingly

- hook into right arrow click to populate new elements
- reflow elements according to width

**Comment by ajayyy** [comment]
Removing `ytd-rich-item-renderer` and `ytd-video-meta-block[rich-meta] #metadata-line.ytd-video-meta-block` from the style seems to have a better effect

**Comment by mchangrh** [comment]
probably died with reflow https://github.com/mchangrh/yt-neuter/commit/e45e79ae4fe7448941808c29b5434e104f9b599b
