### ISSUE TITLE
Search results removed when channel filter is used 

### ISSUE THREAD

**Issue by unbeatable-101** [mchangrh/yt-neuter#30]
https://user-images.githubusercontent.com/58151048/229910372-29f84b8c-4719-463d-8f94-d1550379fa7a.mov

Doesn't happen in a general search, but does when filtered to channels only

**Comment by mchangrh** [comment]
This is intentional behavior for general search but I'll look into adding an exclusion for channel searches

https://github.com/mchangrh/yt-neuter/blob/882263429a35fbc8fab61bf605c1603ea9b096b5/yt-neuter.txt#L314-L315

**Comment by mchangrh** [comment]
also breaks https://www.youtube.com/feed/channels
