### ISSUE TITLE
Big Video Info

### ISSUE THREAD

**Issue by barraIhsan** [mchangrh/yt-neuter#35]
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/65c1d87f-c4be-436d-88a5-2fe421e42f58)
I dont know what to call it, but basically its the big video info at the bottom of the description

**Comment by barraIhsan** [comment]
Hmmm, the "More from Channel" video is also blocked because of this.
Does it possible to just block the channel name, subscriber, logo, video button and about?
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/2c2a28de-4875-472e-9595-dfdfb8a09051)
Example "More from Channel". If this whole is blocked, when you pressed the i card thing, it will not show up the video

**Comment by mchangrh** [comment]
I'll see what I can do to make it more specific but it looks like it shares
most of the markers

**Comment by barraIhsan** [comment]
> but it looks like it shares most of the markers

yes, its shares. And your new filter still doesnt work.
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/9466e4e6-f4b6-4e8c-b355-95d6d94f9edd)
It will select all of it

**However**, I decided to try and it works. This is my filter
`youtube.com##ytd-video-description-infocards-section-renderer > :not(#infocards-section)`
and it works!
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/3ce07341-73d4-4f8e-aa57-8cb96ad69864)

---

There is something tho, there is #social-links, but somehow it always greyed (hidden) in many video I tried. So probably just block it too? Or if its also excluded, the filter would look something like this
`youtube.com##ytd-video-description-infocards-section-renderer > :not(#infocards-section):not(#social-links)`

![image](https://github.com/mchangrh/yt-neuter/assets/57800056/80c2179f-bda1-443e-837c-2a814e30bd9e)

**Comment by barraIhsan** [comment]
Just to add up
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/f4a36305-8703-4a78-b9cb-5ec6d1de90d7)
is this a typo (a space after `.`) that make it to be error?

**Comment by mchangrh** [comment]
The problem with your filter is that the larger element will still remain padded

**Comment by barraIhsan** [comment]
> still remain padded

what gap?
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/757780a9-f30b-4a1e-9718-0066e8fbb4d9)
it works fine. Did you mean the `hr` when there is no info card?
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/0c7d30fb-d459-42cd-ac1e-3f16e0fc590f)

**Comment by mchangrh** [comment]
Can you send the link to this video? I've only been getting the channel popup and not the recommendations so Its been a beat guess effort to try and excuse those extra boxes.

**Comment by mchangrh** [comment]
oh I see. I assume you want to preserve info cards and social links, only removing the channel banner?
