### ISSUE TITLE
[Bug] Blocked "Save" Button on Youtube Comment

### ISSUE THREAD

**Issue by barraIhsan** [mchangrh/yt-neuter#36]
## Bug
The bug is basically hide the "greyed out" Submit button on comment. And **completely** removed the Save button on comment editing.

### With YouTube Neuter filter turned on:
Comment w/o content
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/fbff1f65-5033-4ae8-8573-2c325c270ce7)
Comment w/ content (expected behaviour)
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/25d8441b-c3fb-4548-ac94-28805f63dcd3)
Edit the comment w/ AND w/o content changed (the "Save" button just disappeared)
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/014bcebe-8bd3-4e60-953d-771e5b1eb420)

### With Youtube Neuter filter turned off:
Comment w/o content ("Submit" button should come up, but its grayed out)
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/1464f32b-cb47-42fa-b8ac-a4469824c18f)
Comment w/content (the same)
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/4ad3681b-99b6-4036-b354-caceb6f37fcf)
Edit the comment w/o content changed ("Save" greyed out)
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/6a3ec7ae-b0b1-4ed8-9e1f-bc2064e1bbe7)
Edit the comment w/ content changed (There is "Save" button)
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/907b21d5-4c67-43df-90f4-fc739a101fd5)

**Comment by mchangrh** [comment]
Do you just have the base neuter filter enabled?

**Comment by mchangrh** [comment]
found the offending lines
https://github.com/mchangrh/yt-neuter/blob/2374e8c1a778adab6f070aa2060f47e8635dd6fa/yt-neuter.txt#L154-L155

**Comment by barraIhsan** [comment]
1. The edit comment, still blocked the "Save" button (w/ and w/o change)
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/d07069ae-ba6d-4ecf-a3f2-61c084596b92)
2. Did you just remove the `youtube.com` in the filter?
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/e5c720c1-0104-4997-a967-77d16c3a52d7)

**Comment by mchangrh** [comment]
the commentbox exclusion works for the save as well as comment box for me

**Comment by barraIhsan** [comment]
the edit still doesnt work.
Tried with fresh firefox profile, still hides. The normal comment button works tho, but not the editing

https://github.com/mchangrh/yt-neuter/assets/57800056/c05b2b01-f29c-4c3b-8e97-ed50d8e27ce3

**Comment by mchangrh** [comment]
It's possible that ublock origin pulled an older version since the timestamp did not update - click on the eye icon and search for `:not(.ytd-commentbox)` - I can't replicate locally

**Comment by barraIhsan** [comment]
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/7c1b8f80-665e-4e42-8ecd-c474f2e7f5a5)
Maybe a firefox bug? also why the yellow part highlighted?

**Comment by mchangrh** [comment]
starting to sound like a firefox bug, will test on my install

**Comment by mchangrh** [comment]
wrong filter, it's the save button.

**Comment by mchangrh** [comment]
fixed in https://github.com/mchangrh/yt-neuter/commit/e5ea33cc828e20cc69863e61e0903ee9c1a513bf

**Comment by barraIhsan** [comment]
nice! it works. It seems is capturing both "Save" lmao
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/2ca66b45-40f6-45df-9a3d-d2e1afce47c3)

**Comment by barraIhsan** [comment]
For the save button (not collapsed)
`##ytd-button-renderer:has(>yt-button-shape:has(> button[aria-label="Save to playlist"]))` (the aria-label for save is not `Save`, but `Save to playlist`)
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/f52ca740-f188-4e07-85d7-29cda1b01867)
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/648d6a46-4688-4564-b5f3-7b95e731dad5)
Save button on editing comment safe 👍 

and for the save button that collapsed under ... (overflow)
`##ytd-menu-service-item-renderer:has(>tp-yt-paper-item:has(>yt-formatted-string:has-text(Save)))` (to make it the same like the rest of the interaction row)
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/d4f85dab-783f-46e3-be61-4e19c2bfd34f)
Again, "Save" button on editing comment safe

**Comment by mchangrh** [comment]
Some of these are for older versions, some are targeting overflows

**Comment by barraIhsan** [comment]
ok, but the original problem is resolved, but the save button appear again (see the top of the comment), I think there is no need making new issue.

**Comment by mchangrh** [comment]
non-overflow save button removed in https://github.com/mchangrh/yt-neuter/commit/695b0f8c198306eb36a1a81bedcab53c85771226

**Comment by barraIhsan** [comment]
ok
