### ISSUE TITLE
[Bug] Featured Playlist blocked Chapters, Large Channel Info Cards

### ISSUE THREAD

**Issue by barraIhsan** [mchangrh/yt-neuter#37]
The current filter is `##ytd-structured-description-content-renderer:has(ytd-structured-description-playlist-lockup-renderer)`. And if we see, it will block chapters, and also the large channel info cards.
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/367e7ea7-2d8a-4398-b48c-ac87d2d3e448)
<details>
<summary>Additional info</summary>

![image](https://github.com/mchangrh/yt-neuter/assets/57800056/e4f4f854-ba5f-4d2a-a71f-27a38d05e6fb)
Apparently, "featured playlist" filter also capture when there is featured music, what?

</details>

The filter should be like the Large Channel Info Cards (#35), and also Featured Music
New filter: `##ytd-video-description-course-section-renderer` (shorter 👍)
And now, it will only block the featured playlist.
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/56037cde-0e4f-4d7f-a7d1-ea5d81eff582)

**Comment by mchangrh** [comment]
oh nice, this is an old rule from before the description box overhaul

**Comment by mchangrh** [comment]
closed in https://github.com/mchangrh/yt-neuter/commit/7234b6a72897f9c95cd3934b1d0a901337f0f2ea
