### ISSUE TITLE
[Question] What is annotation?

### ISSUE THREAD

**Issue by barraIhsan** [mchangrh/yt-neuter#39]
What is annotation filter? Its seems its just block the endcards.
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/0f714077-5776-480a-880d-940ad56fb4bf)
Why annotation is not in the "endscreen" filter? It literally just block the endscreen (maybe)
Also, in the "endscreen" filter, the `endscreen.js` is blocked. But its still showing up the endscreen? Idk why its blocked in the "endscreen" filter
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/885cb3a2-e024-42ec-a1a4-ef81ec2e448f)

**Comment by mchangrh** [comment]
annotations are clickable elements, usually featured on the endcards while it is still showing the video by the creator

endscreen.js is after the endcards where it is all youtube recommendations

**Comment by barraIhsan** [comment]
Oh, I get it now. Thanks
