### ISSUE TITLE
Invalid Filter: Unexpected Input on Line 66 of YouTube Neuter - misc

### ISSUE THREAD

**Issue by jessebodin** [mchangrh/yt-neuter#47]
https://github.com/mchangrh/yt-neuter/blob/ba67d36a24fbb302cf5d55b107ee1eefa54e1e98/filters/misc.txt#L66C135-L66C135

uBlock Origin is warning _Invalid Filter: Unexpected Input_ on this line. I think the comment just needs to be moved to a new line.

**Comment by mchangrh** [comment]
ah, that's just a bad copy that got hidden under the long filter, Thanks!
