### ISSUE TITLE
Hide Transcript on Description

### ISSUE THREAD

**Issue by barraIhsan** [mchangrh/yt-neuter#48]
![image](https://github.com/mchangrh/yt-neuter/assets/57800056/494fa3e3-b4cc-4960-ade8-aa7e576ebc08)

**Comment by mchangrh** [comment]
this was deliberately included, I'll try to remove this one and keep the overflow menu one since it's less intrusive

**Comment by ajayyy** [comment]
The overflow menu one is gone
