### ISSUE TITLE
Filter Update: Block youtube "enhanced bitrate Premium" popup spam

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [mchangrh/yt-neuter#49]
a while ago I started to get harassed by these every single time I seek or paused any video
![bqcabVq](https://github.com/mchangrh/yt-neuter/assets/2242880/6ea354d2-9492-4b12-a7ae-b95aba7307d1)

you can see how often i get spammed by this [video demo](https://replay.dropbox.com/share/NTPBzg4M4i4b2CFB?video_version_id=pid_rvv%3AAAAAAGVTJkkfNxcuF1sQD4HQ-7DmnWlQgrBmjNzqUlKM1bRo).

now i think I've got the rule setup right:
```
youtube.com##ytd-popup-container > tp-yt-paper-dialog:has(ytd-offline-promo-renderer)
youtube.com##.opened
```
the `.opened` class is to stop the black flicker every time ublock or any adblocker blocks the main element. its very noticeable.

I'm mainly using your sponsor block as i find the main one too aggressive for my needs.

**Comment by mchangrh** [comment]
Interesting, I'll try to replicate it and check if I can find it in the source code

**Comment by XxUnkn0wnxX** [comment]
> I believe it might be `ytd-video-quality-promo-renderer`, can you try that instead?
> 
> ```
> youtube.com##ytd-video-quality-promo-renderer
> ```

nah I still get the popup with that, I'm pretty sure it's

you can also do it via 
```
youtube.com##ytd-offline-promo-renderer
```
however 
```
youtube.com##.opened
```
still needs to be blocked to stop the annoying flickering..

it's both div element ID & class
<img width="2118" alt="Screen Shot 2023-11-27 at 4 44 07 pm" src="https://github.com/mchangrh/yt-neuter/assets/2242880/786e8fea-34c3-4000-8b62-27c94d4831d8">

**Comment by mchangrh** [comment]
oh okay, the HTML hump helps a lot, let me see if I can target the parent instead

**Comment by mchangrh** [comment]
how's
```
youtube.com##ytd-popup-container:has(>tp-yt-paper-dialog>ytd-offline-promo-renderer)
```

that should block the popup, if you could send the HTML for the overlay backdrop that would be great, I'm hesitant to block something as large as the overlay-backdrop and I don't see any flags I can enable to reproduce your personal hell of premium popups

**Comment by XxUnkn0wnxX** [comment]
> how's
> 
> ```
> youtube.com##ytd-popup-container:has(>tp-yt-paper-dialog>ytd-offline-promo-renderer)
> ```
> 
> that should block the popup, if you could send the HTML for the overlay backdrop that would be great, I'm hesitant to block something as large as the overlay-backdrop and I don't see any flags I can enable to reproduce your personal hell of premium popups

ya `youtube.com##ytd-popup-container:has(>tp-yt-paper-dialog>ytd-offline-promo-renderer)` works

if you want here is the whole page dump with no filtering on how it renders for me:
[page dump.html.zip](https://github.com/mchangrh/yt-neuter/files/13470672/page.dump.html.zip)

but ya the flickering still occurs without blocking `tp-yt-iron-overlay-backdrop` at least.

**Comment by mchangrh** [comment]
I think 
```
youtube.com##tp-yt-iron-overlay-backdrop.opened
```

would be the best of both worlds 😆 - catches backdrop and `.opened`

if there are no issues, I'll also merge it in without opened for better compatibility

**Comment by mchangrh** [comment]
added in https://github.com/mchangrh/yt-neuter/commit/979f38a01592ff1509d10cfd24cf2f20b1d40dcf
