### ISSUE TITLE
`Community` Tab

### ISSUE THREAD

**Issue by NormTurtle** [mchangrh/yt-neuter#52]
For some reasaon i wanat to use `Community` tab , and i just can't use it until i off ublock with script
is there anyway user can get costomized experience
or just performace tweak , not the usability or looks tweak !

**Comment by mchangrh** [comment]
I have considered making it into a browser extension but I'm not too keen on the additional maintenance needed

as for excluding filters, you can exclude any filter with the `#@#` syntax
in your case

```adguard
! community posts
youtube.com#@#ytd-rich-shelf-renderer:has(ytd-rich-item-renderer[is-post])
! community tab
youtube.com#@#tp-yt-paper-tab:has(> .tab-content:has-text(Community))
youtube.com#@#yt-tab-shape[tab-title="Community"]
```

**Comment by NormTurtle** [comment]
i am not sure what plan Your up-to
but, i guess i got my answer.
