### ISSUE TITLE
yt-neuter hiding subscribe/unsubscribe button when activated

### ISSUE THREAD

**Issue by vico93** [mchangrh/yt-neuter#53]
I'm using this list on ublock origin, and when i activate it the subscribe/unsubscribe button dissapear from both channel and video pages. Deactivating it makes the button reappear.

With yt-neuter ON:
![image](https://github.com/mchangrh/yt-neuter/assets/3485505/211a2283-269a-4000-94b0-9ecca690decf)

With yt-neuter OFF:
![image](https://github.com/mchangrh/yt-neuter/assets/3485505/0bc761df-c24b-4969-b82d-03a6e7e3df72)

**Comment by PasttaTypo** [comment]
Yup, although it's only disappearing if you've subscribed to them.

**Comment by ZomoXYZ** [comment]
> youtube.com##yt-animated-action is the culprit in filter rules.

I can confirm this is the issue, commenting this line out after putting it all in My Filters allows me to see the Subscribed button

**Comment by mchangrh** [comment]
hiding the subscribe but not the unsubscribe button is intentional. The filter is

```
#@#subscribe-button
```

relevant commit https://github.com/mchangrh/yt-neuter/commit/3869c2650d0e58cca92e03b9538d9da73d6ab1c9

**Comment by EpicLPer** [comment]
> hiding the subscribe but not the unsubscribe button is intentional. The filter is
> 
> ```
> #@#subscribe-button
> ```
> 
> relevant commit [3869c26](https://github.com/mchangrh/yt-neuter/commit/3869c2650d0e58cca92e03b9538d9da73d6ab1c9)

Not entirely sure why this should be intentional behavior, especially when it's hiding the button to unsubscribe when I'm already subscribed to a channel, which it currently does.
That said Subscriptions are a good thing, not a bad one. Plus hiding it would actually hurt the creator more than the end-user.

**Comment by mchangrh** [comment]
You need to reload to unhide elements after toggling uBo. I'll try to debug when I get home.

My mindset of neuter exists devoid of any creators - half of the elements in your screenshot are hidden by various filters. If the baby must be thrown out with the bathwater. Let it be so.
