### ISSUE TITLE
HIde Merch Section

### ISSUE THREAD

**Issue by zkisaboss** [mchangrh/yt-neuter#54]
This fixes the visual bug by blocking the entire merch shelf, including additional padding.
`##ytd-merch-shelf-renderer.ytd-watch-flexy.style-scope`

Example Video: [Game Theory: Why Everyone HATES YouTube Shorts… And You Should Too!](https://www.youtube.com/watch?v=0Igj3qI0GBA)

**Comment by mchangrh** [comment]
https://github.com/mchangrh/yt-neuter/commit/8544c6a8821958e6158d3bce967df6609523ff06
