### ISSUE TITLE
Rule `youtube.com##yt-animated-action` hides the subscribe button entirely

### ISSUE THREAD

**Issue by kotx** [mchangrh/yt-neuter#55]

**Comment by kotx** [comment]
Duplicate of https://github.com/mchangrh/yt-neuter/issues/53 but should mention this in README?

**Comment by mchangrh** [comment]
It should have been reverted. Oh I didn't remove it from the sponsorblock filter

**Comment by mchangrh** [comment]
Tagged the wrong issue but https://github.com/mchangrh/yt-neuter/commit/5d2edbc2741ebc43d936573550de680af12e6433

let me know if it fixes it

**Comment by kotx** [comment]
@mchangrh Yup, it works now. Thanks!
