### ISSUE TITLE
Filter List disabling read more option in YT comments that exceed normal length

### ISSUE THREAD

**Issue by PasttaTypo** [mchangrh/yt-neuter#57]
_Read More_ option disappearing w/ SponsorBlock filterlist enabled unless video page is a direct link or tab is reloaded.
_Tested with SponsorBlock list on and off, Vivaldi Browser_

Filter List disabled:
<img src="https://github.com/mchangrh/yt-neuter/assets/125756085/1444d228-6bc1-4031-964b-4fefe922ef56" width="500"/>
Enabled (missing Read More):
<img src="https://github.com/mchangrh/yt-neuter/assets/125756085/9ead5018-f871-4b10-825d-0209fb2c9f99" width="500"/>

**Comment by mchangrh** [comment]
that is odd, I'm not seeing it blocked with all the other filters on as well. Can you send the video? I think it might be the pinned comment that is interfering

**Comment by mchangrh** [comment]
which adblocker are you using? could it be misinterpreting
```adguard
youtube.com##ytd-comment-renderer#comment:style()
```
and excluding the style selector?

**Comment by PasttaTypo** [comment]
> which adblocker are you using? could it be misinterpreting
> 
> ```
> youtube.com##ytd-comment-renderer#comment:style()
> ```
> 
> and excluding the style selector?

No, weirdly I found that adding `youtube.com##yt-tooltip-renderer[slot="dropdown-content"]` as an exception allowed the Read More option to display again. I'm using UBlock Origin.

**Comment by mchangrh** [comment]
looks like #12 wasn't specific enough

**Comment by mchangrh** [comment]
removed from filter lists, I'll have to try to recreate it and get a better filter for that
