### ISSUE TITLE
[Bug] Hiding save button

### ISSUE THREAD

**Issue by zkisaboss** [mchangrh/yt-neuter#58]
```
##yt-button-view-model:has(>button-view-model> button[aria-label=Save])
```
 should be replaced with 
```
##yt-button-view-model:has(>button-view-model> [aria-label='Save to playlist'])
```

**Comment by mchangrh** [comment]
Thanks!

**Comment by RenaKunisaki** [comment]
Seems to be happening again. No save options anywhere.

**Comment by mchangrh** [comment]
No save options is the intended outcome, if you want to add an exclusion copy the rule above and replace ## with #@#

**Comment by RenaKunisaki** [comment]
I don't see a way to edit the rules while still having automatic updates. Is that possible?

**Comment by mchangrh** [comment]
Adding it to your local filter list as an exclusion will still let the other filters work
