### ISSUE TITLE
Hide 'Latest Shorts from' in search results

### ISSUE THREAD

**Issue by OfficerGoose** [mchangrh/yt-neuter#59]
![image](https://github.com/mchangrh/yt-neuter/assets/94632011/5d60e187-c04d-459a-9c54-179b13dc3f6b)

I don't think there is a filter to block this yet, so I bringing this to your attention since there is already filter for 'latest from channel' in search results.

**Comment by mchangrh** [comment]
this would be part of the [noshorts](https://github.com/mchangrh/yt-neuter/blob/main/filters/noshorts.txt) filter list and should already be blocked under generics > shelves > generic short shelf
