### ISSUE TITLE
Use www.youtube.com for desktop-only filters

### ISSUE THREAD

**Issue by metametapod** [mchangrh/yt-neuter#65]
I was comparing YouTube Neuter - noshorts to a previous list I had been using ([`letsblock.it - YouTube: filter out Shorts`](https://letsblock.it/filters/youtube-shorts), soon to be defunct unless someone takes the project over), and noticed they use `www.youtube.com` for the desktop-only filters instead of `youtube.com`.

Should yt-neuter do the same? I think that would cut down on extraneous rules on mobile, for example all `#ytd-*` rules don't apply if I understand correctly.

**Comment by mchangrh** [comment]
I believe the only real subdomain is `m.` and `tv.` but I haven't tested any filters against `tv.` Aside from some request blockers it should speed up mobile filters

**Comment by mchangrh** [comment]
Left a few filters alone because they're generic and I added them based on CSS name, but now most of them (which are desktop-specific) are now desktop specific :)

**Comment by mchangrh** [comment]
Cleaned up the rest of ytd-

https://github.com/mchangrh/yt-neuter/commit/f97bd5f949b023f1830b89c39ca6fd399586d787

Still a few remaining generic filters that were ripped from CSS
