### ISSUE TITLE
False positive jnn-pa.googleapis.com

### ISSUE THREAD

**Issue by usermyname12** [mchangrh/yt-neuter#68]
The following filters prevent video playback at some videos. The video loads but then gives an error after a few seconds.

||jnn-pa.googleapis.com/$rpc/google.internal.waa.v1.Waa/Create$xhr
||jnn-pa.googleapis.com/$rpc/google.internal.waa.v1.Waa/GenerateIT$xhr

**Comment by mchangrh** [comment]
I love anti-adblock
