### ISSUE TITLE
Randomly blocking entire recommendation bar

### ISSUE THREAD

**Issue by CountingBeeps** [mchangrh/yt-neuter#76]
This just started for me, but it started blocking all of the recommended videos in the recommendations bar on random videos and somtimes when I scroll down to far. Happy to provide any other info you need.

**Comment by mchangrh** [comment]
Yep, it was reported by another user as well. Seems to be a side effect of #75, should be fixed in https://github.com/mchangrh/yt-neuter/commit/ee25ad55c8f03b7a6d58af6e6b7f996d7e29e36e
